# ===============================
# = Spring configurations
# ===============================
spring:
  name: local
  # = HTTP requests configurations ##############################
  servlet:
    multipart:
      location: /tmp
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: openfabric
    password: 9c231a1c61a5fe322dd1
